### ISSUE TITLE
rgba(10,10,10,1) is not accepted as valid value

### ISSUE THREAD

**Issue by anvmn** [christian-bromann/rgb2hex#10]
![selection_999 1311](https://user-images.githubusercontent.com/17882245/42335925-9faaa0c0-808a-11e8-8cc4-c033d2d0d155.png)

**Comment by anvmn** [comment]
The problem is with regular expression:
`var digits = /(.*?)rgb(a)??\((\d{1,3}),(\d{1,3}),(\d{1,3})(,[01]??\.([0-9]{0,3}))??\)/.exec(strippedColor);`

It does not allow 1 as fourth rgb parameter.

**Comment by christian-bromann** [comment]
Fixed with v0.1.8
