### ISSUE TITLE
given color (rgba(0, 0, 0, 0)) isn't a valid rgb or rgba color

### ISSUE THREAD

**Issue by goonyaa** [christian-bromann/rgb2hex#11]
Hello.

Not sure if I need to post it here or in webdriverio but still.

I have an element with `background-color: transparent` and when I'm doing `getCssProperty` with webdriverio I'm getting the error: `given color (rgba(0, 0, 0, 0)) isn't a valid rgb or rgba color`. 

Right now I have latest version of rgb2hex (0.1.8), and I'm sure there were no issue at least for 0.1.4 version. And looking at current regexp in input parse it definitely should throw this error and everything will be fine for something like rgba(0, 0, 0, 0.0) for example.

So, I'm not sure if I need to do something with my styles or regexp for parsing should be changed.

Thanks.

**Comment by christian-bromann** [comment]
Just published a new version (v0.1.9) that supports transparent colors. Please update your rgb2hex dependency.
