### ISSUE TITLE
background url breaks the stripping of values

### ISSUE THREAD

**Issue by radiovisual** [christian-bromann/rgb2hex#8]
Attempting to strip the color out of a value like this:

```
rgb(226,230,233)url("https://foo.bar.com")no-repeatscroll0%0%/100%padding-boxborder-box
```
```
rgba(226,230,233,0.4)url("https://foo.bar.com")no-repeatscroll0%0%/100%padding-boxborder-box
```

will result in the `... isn't a valid rgb or rgba color`, this is because [the module looks for the `lastIndexOf(')')`](https://github.com/christian-bromann/rgb2hex/blob/master/index.js#L26), which in this case, would be the last parenthesis in the `url()` of a background. 

so changing `lastIndexOf` to `indexOf` seems to be more appropriate.

**Comment by christian-bromann** [comment]
This was fixed and merged. Thanks!
